spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never
  tomcat:
    threads:
      max: 20

logging:
  level:
    academy.devdojo: debug

database:
  url: jdbc:mysql://localhost:3306/anime_db
  username: devdojo
  password: devdojo